sudo: required
language: python
python:
  - "3.6"
services:
  - docker

install:
  - pip install -r requirements.txt

before_script:

script:
  - pytest
  - npm install -g snyk
#  - snyk test
#  - docker build -t sierra-nginx . --no-cache=True

after_success:
#  - snyk monitor
  - radon cc sierra*.py -as
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -f Dockerfile -t sierra-nginx . --no-cache=True
  - docker images
  - docker tag sierra-nginx $DOCKER_USERNAME/sierra-nginx
  - docker push $DOCKER_USERNAME/sierra-nginx
  - docker run -p 127.0.0.1:80:5000 -d -t $REPO
  - docker ps -a
  - curl -v 127.0.0.1:80

