dist: trusty
sudo: required
language: python
python:
  - "3.6"

# Git safelist
branches:
  only:
  - master

git:
  depth: 2

services:
  - docker

addons:
  sonarcloud:
    organization: "robster970-github"

before_install:
  - pip install pytest pytest-cov
  - pip install coveralls

install:
  - pip install -r requirements.txt

before_script:
  - npm install -g snyk
  - mkdir .output && cd .output/ && ls -lart && cd ..

script:
  - pytest --cov-config .coveragerc --cov-report xml --cov=. test_sierra.py --verbose
  - sonar-scanner
  #- snyk test

cache:
  directories:
    - '$HOME/.sonar/cache'

after_success:
  - coveralls
  #- snyk monitor
  - radon cc sierra*.py -as
  - rm coverage.xml
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -f Dockerfile -t sierra-nginx . --no-cache=True
  - docker images
  - docker tag sierra-nginx $DOCKER_USERNAME/sierra-nginx
  - docker push $DOCKER_USERNAME/sierra-nginx
  - docker run -p 127.0.0.1:80:5000 -d -t $DOCKER_USERNAME/sierra-nginx
  - docker ps -a
  - curl -v 127.0.0.1:80/source=S

